### PR TITLE
Modify index.html and styles.css

### PR DESCRIPTION
**Pull request by fpsapc**
Modify index.html and styles.css to get accessibility results 100%.

•	[Page titles](https://www.w3.org/WAI/test-evaluate/preliminary/#title)	(no issue found)
•	[Image text alternatives** (alt text)](https://www.w3.org/WAI/test-evaluate/preliminary/#images)
following is the link of changes I just made. I put alt text to all my img tags. https://github.com/fpsapc/MicroverseStudentProject1/compare/accessibility?expand=1#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R85

•	[Text headings](https://www.w3.org/WAI/test-evaluate/preliminary/#headings) (no issue found)
•	[Color contrast](https://www.w3.org/WAI/test-evaluate/preliminary/#contrast) 
Following is the link that changes I made to make the color contrast good.
https://github.com/fpsapc/MicroverseStudentProject1/compare/accessibility?expand=1#diff-37f6471b306924bbb531d040e7ab55df5f83511246a411d22947462323516afaR208

•	[Resize](https://www.w3.org/WAI/test-evaluate/preliminary/#resize) (no issue found)
•	[Interaction](https://www.w3.org/WAI/test-evaluate/preliminary/#interaction) (no issue found)
•	[Moving content](https://www.w3.org/WAI/test-evaluate/preliminary/#moving) (no issue found)
•	[Multimedia](https://www.w3.org/WAI/test-evaluate/preliminary/#media) (no issue found)
•	[The basic structure of the page](https://www.w3.org/WAI/test-evaluate/preliminary/#structure) (no issue found)

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] Kindly note that this is a `pair programming` activity and each of you should have at least one commit message.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by xandro2021** [comment]
I was the navigator in the first part, but now I did my commit :)

**Review by huseyinbiyik — CHANGES_REQUESTED** [review]
Hi @fpsapc  and @xandro2021,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
Almost there

## Highlights
- You shared the reports of all results 👍 
- You explained the parts you amended 👍 

## Required Changes ♻️
- Good job using heading elements. But let's not forget this one. This is showing us that there is a new section includes your works. So it deserve a hierarchical heading element like h2 or h3, according to importance.
Screenshot 2023-02-28 at 8 05 40 PM
- As mentioned [here](https://www.w3.org/WAI/test-evaluate/preliminary/#interaction), you need to navigate through the links with TAB key on the page.  Currently, it is skipping the email ✉️ button. Kindly fix that 👍 
Screen Recording 2023-02-28 at 8 15 53 PM

- Even if you amend the accessibility of your buttons there are some fails in the color contrast. Here is the [result](https://www.aditus.io/button-contrast-checker/raw-githack-com-2023-02-28-at-17-07-50-000) that I can share with you. Kindly fix those 👍 


_Check the comments under the review._

## Optional suggestions
- Since you didn't start to implement mobile nav, I will keep it optional. I highly recommend to add alt text to the close button. 👍 
Screenshot 2023-02-28 at 8 33 33 PM

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by BregornOriginal — APPROVED** [review]
## Hi @Team 💯 💯 💯 

## Your project is complete!  There is nothing else to say other than... it's time to merge it 

## Congratulations! 

IPhi

## Highlights

✅ Linters are passing
✅ Good commit history
✅ Good work making the changes requested by previous reviewer


## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
Cheers and Happy coding!:aplauso::aplauso::aplauso:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)[.](https://airtable.com/shrQAqnBwek5a0O0s)._)

**Pull request merged**
